export const feedbackPhrases = {
  positive: {
    'Serving': [
      "The service was outstanding and extremely prompt.",
      "The staff served us with a warm smile and great efficiency.",
      "Food arrived quickly and was served perfectly.",
      "The server was highly attentive to all our needs.",
      "Service was impeccable from start to finish.",
      "We were served right away without any delays.",
      "The waitstaff was incredibly polite and quick.",
      "Exceptional service, they really went above and beyond.",
      "The serving speed was fantastic.",
      "I was very impressed with how well we were served.",
      "Service was top-notch and highly professional.",
      "Our server was friendly and made sure we had everything.",
      "Quick, efficient, and very pleasant service.",
      "The food was brought out hot and perfectly timed.",
      "Great attention to detail by the serving staff.",
      "The hospitality during service was remarkable.",
      "We never had to ask for anything twice.",
      "Excellent table service throughout our visit.",
      "The team worked seamlessly to provide great service.",
      "Truly 5-star serving quality."
    ],
    'Staff Behaviour': [
      "The staff was incredibly welcoming and kind.",
      "Everyone working here was so polite and helpful.",
      "The team went out of their way to make us comfortable.",
      "Extremely professional and courteous staff.",
      "The employees had such a positive and friendly attitude.",
      "Great customer service and fantastic staff behavior.",
      "The staff made us feel right at home.",
      "Very respectful and accommodating personnel.",
      "I loved how cheerful and helpful the staff were.",
      "The team was attentive, smiling, and very gracious.",
      "Outstanding hospitality from every staff member.",
      "The workers here clearly care about their guests.",
      "We were greeted with warmth and genuine smiles.",
      "Staff behavior exceeded all my expectations.",
      "They handled our requests with absolute professionalism.",
      "The crew was fantastic, very approachable.",
      "Such a delightful team of people working here.",
      "The staff's polite nature really stood out.",
      "Exceptional manners and excellent communication.",
      "The personnel were the highlight of our experience."
    ],
    'Cleaning': [
      "The premises were absolutely spotless.",
      "Everything was exceptionally clean and well-maintained.",
      "You can tell they take cleanliness very seriously here.",
      "The environment was hygienic and sparkling clean.",
      "Immaculately clean from top to bottom.",
      "The hygiene standards are truly impressive.",
      "I was amazed at how tidy and neat everything was.",
      "The cleaning staff does an incredible job.",
      "Not a speck of dust to be found anywhere.",
      "The facilities were incredibly fresh and sanitized.",
      "Great job maintaining such a clean space.",
      "The cleanliness made me feel very comfortable.",
      "A wonderfully pristine and hygienic environment.",
      "The attention to cleanliness is highly commendable.",
      "Everything shined, proving great cleaning protocols.",
      "Very sanitary and well-kept facilities.",
      "The cleaning standards here are top tier.",
      "Smelled fresh and looked absolutely flawless.",
      "Perfectly sanitized, which is so important to me.",
      "The immaculate cleanliness really elevated the experience."
    ],
    'Room Quality': [
      "The room was spacious, comfortable, and beautifully designed.",
      "Absolutely loved the room, it was perfect.",
      "The bed was incredibly comfortable and the room was great.",
      "Fantastic room quality with excellent amenities.",
      "The room felt very luxurious and cozy.",
      "Everything in the room worked perfectly and looked modern.",
      "A truly premium room experience.",
      "The room was well-lit, airy, and very welcoming.",
      "High-quality furniture and a very relaxing atmosphere.",
      "The room exceeded my expectations in every way.",
      "Beautiful decor and a very comfortable space.",
      "The room was quiet, peaceful, and well-equipped.",
      "Great attention to detail in the room's design.",
      "The mattress and pillows were of excellent quality.",
      "A wonderfully arranged room that felt like home.",
      "The aesthetics and comfort of the room were 10/10.",
      "Very well-appointed room with everything we needed.",
      "The quality of the room made our stay so much better.",
      "Gorgeous room with a fantastic layout.",
      "Top-notch room facilities and superb comfort."
    ]
  },
  negative: {
    'Serving': [
      "The service was incredibly slow and frustrating.",
      "We had to wait way too long to be served.",
      "The serving staff was inattentive and hard to find.",
      "Our orders were delayed significantly.",
      "The service was disorganized and chaotic.",
      "We felt ignored by the serving staff.",
      "The food took forever to arrive at our table.",
      "Poor service, we had to ask for things multiple times.",
      "The serving speed really needs improvement.",
      "The staff seemed overwhelmed and service suffered.",
      "We experienced very delayed and poor table service.",
      "The servers forgot part of our order.",
      "Getting someone's attention for service was difficult.",
      "The serving experience was quite disappointing.",
      "Unacceptable wait times for basic service.",
      "The service lacked professionalism and speed.",
      "We were not served in a timely manner.",
      "The serving process was highly inefficient.",
      "Terrible service, it completely ruined the experience.",
      "The waitstaff needs better training on serving promptly."
    ],
    'Staff Behaviour': [
      "The staff was quite rude and unhelpful.",
      "I experienced very unprofessional behavior from the team.",
      "The employees seemed annoyed when we asked questions.",
      "Staff attitude was poor and unwelcoming.",
      "We were treated with a lack of respect.",
      "The personnel lacked basic customer service skills.",
      "The staff was argumentative and impolite.",
      "I was very disappointed by how the staff treated us.",
      "The workers were dismissive and unaccommodating.",
      "Terrible hospitality and unfriendly staff.",
      "The team seemed completely uninterested in helping us.",
      "Staff behavior was unacceptable and offensive.",
      "We encountered very grumpy and hostile employees.",
      "The staff lacked empathy and basic manners.",
      "Customer service here is severely lacking.",
      "The employees need an attitude adjustment.",
      "We felt very unwelcome due to the staff's behavior.",
      "The front-line staff was highly unprofessional.",
      "I was shocked by the poor attitude of the team.",
      "The staff made our experience very unpleasant."
    ],
    'Cleaning': [
      "The place was quite dirty and poorly maintained.",
      "I noticed a severe lack of basic cleanliness.",
      "The hygiene standards here are completely unacceptable.",
      "The premises were dusty and looked uncleaned.",
      "The cleanliness left a lot to be desired.",
      "There were obvious stains and dirt everywhere.",
      "The facilities felt very unsanitary.",
      "It doesn't look like they clean this place properly.",
      "The cleanliness was shockingly bad.",
      "We found the environment to be quite filthy.",
      "Poor housekeeping and lack of hygiene.",
      "The lack of cleanliness made me very uncomfortable.",
      "Trash was overflowing and surfaces were sticky.",
      "The cleaning staff is clearly not doing their job.",
      "Very dusty and generally unclean atmosphere.",
      "The hygiene protocols here are severely failing.",
      "I was disgusted by the lack of cleanliness.",
      "The place desperately needs a deep clean.",
      "Unsanitary conditions that need immediate attention.",
      "The poor cleanliness ruined the whole experience."
    ],
    'Room Quality': [
      "The room was in poor condition and felt outdated.",
      "The bed was very uncomfortable and the room was cramped.",
      "Poor room quality, things were broken or malfunctioning.",
      "The room smelled bad and felt very claustrophobic.",
      "The furniture was old, worn out, and damaged.",
      "The room did not match the pictures at all.",
      "Very noisy room with terrible soundproofing.",
      "The room lacked basic amenities and comfort.",
      "I was highly disappointed by the quality of the room.",
      "The room felt dingy and poorly lit.",
      "The AC/heating in the room was not working properly.",
      "The mattress was lumpy and gave me back pain.",
      "Terrible room layout and very uncomfortable.",
      "The room was incredibly basic and overpriced.",
      "We experienced multiple maintenance issues in the room.",
      "The overall room quality was completely unacceptable.",
      "The room was depressing and badly maintained.",
      "Poor ventilation and a very stale atmosphere in the room.",
      "The room facilities were severely lacking.",
      "I would not recommend staying in this quality of room."
    ]
  }
};
